### PR TITLE
Update Fable and remove Emit attributes

### PR DESCRIPTION
**Pull request by alfonsogarciacaro**
Hi @w0lya! Thanks a lot for the great example and post! :clap: 🥇 :clap:

I understand that sometimes interaction with JS can be a bit tricky, so I've tried to update the code to remove most of the `Emit` attributes. I hope it helps 😸 Please let me know if you have any question.

### CODE REVIEW

**Comment by w0lya** [comment]
Hey @alfonsogarciacaro, you are awesome! Thank you so much for contributing, the code looks much better now 😸 Also, I see [this issue](https://github.com/fable-compiler/Fable/issues/1662) is fixed now, so look forward to re-generating the bindings, updating the article and having fun with this further :)

**Comment by w0lya** [comment]
@alfonsogarciacaro Btw, I am thinking to port more examples, including those that are using more than just Three.js itself.  I can create a repo and structure it like the [pixi one](https://github.com/fable-compiler/samples-pixi) for these. Or do you think it'd be better to organize all the JS library interop-related projects into 1 big repo?

**Comment by alfonsogarciacaro** [comment]
Great, thanks for merging the PR! Hmm, not sure, whatever structure is easiest for you should work. BTW, forgot to tell you there was another Three.js example (a bit old, but I guess it should work with latest Fable too) [here](https://github.com/fable-compiler/samples-browser/blob/master/src/webgl-terrain/App.fs) ([live version](http://fable.io/samples-browser/webgl-terrain/)). Maybe it helps?

**Comment by w0lya** [comment]
Awesome 👍 thanks a lot!

**Pull request merged**
